name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pre-pull Docker images
        run: |
          docker pull minio/minio
          docker pull cypress/included:12.17.4

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Test and build
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Deploy to Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Wait for deployment to stabilize
        run: sleep 10

      - name: Cypress run against live site
        uses: cypress-io/github-action@v6
        with:
          config: video=false
          browser: electron
          headed: false
        env:
          CYPRESS_BASE_URL: https://winter-feather-5776.fly.dev

      - name: Cleanup test data
        run: npm run cleanup-test-data:live

